name: Build Flutter Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'  # 使用最新稳定版本的Flutter

    - name: Modify Flutter configuration
      run: |
        FLUTTER_DIR=$(dirname $(which flutter))
        # 根据最新的Flutter SDK结构更新路径
        FLUTTER_GROOVY_PATH="${FLUTTER_DIR}/cache/pkg/flutter_tools/gradle/src/main/groovy/flutter.groovy"
        if [ -f "$FLUTTER_GROOVY_PATH" ]; then
          sed -i '/if.*ShrinkResources.*/,/end/{//d}' "$FLUTTER_GROOVY_PATH"
        else
          echo "flutter.groovy file not found at path: $FLUTTER_GROOVY_PATH"
          exit 1
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 bison patch gcc

    - name: Prepare build environment
      run: |
        wget https://github.com/Cateners/tiny_computer/releases/download/v1.0.18/debian-xfce.tar.xz
        mkdir -p assets
        split -b 98M debian-xfce.tar.xz assets/debian.tar.xz.

    - name: Build project
      run: |
        flutter build apk --target-platform android-arm64 --split-per-abi --obfuscate --split-debug-info=tiny_computer/sdi

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-apk
        path: build/app/outputs/flutter-apk/app-arm64.apk
