name: Build Flutter Android APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # 检出代码到运行环境

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
      # 使用 subosito 提供的 Flutter Action 安装指定版本的 Flutter

    - name: Modify Flutter configuration
      run: |
        # 直接使用 FLUTTER_ROOT 环境变量，这是 GitHub Actions 预设的环境变量
        FLUTTER_GROOVY_PATH="$FLUTTER_ROOT/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy"
        if [ -f "$FLUTTER_GROOVY_PATH" ]; then
          sed -i '/if.*ShrinkResources.*/,/end/{//d}' "$FLUTTER_GROOVY_PATH"
        else
          echo "flutter.groovy file not found at path: $FLUTTER_GROOVY_PATH"
          exit 1
        fi
      env:
        FLUTTER_ROOT: /opt/hostedtoolcache/flutter/stable-3.22.0-x64
      # 确保 sed 命令中的正则表达式匹配整个 if 代码块

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 bison patch gcc
      # 安装构建过程中需要的依赖
    - name: Prepare build environment
      run: |
        wget https://github.com/Cateners/tiny_computer/releases/download/v1.0.18/debian-xfce.tar.xz
        split -b 98M debian-xfce.tar.xz assets/debian.tar.xz.
        mkdir -p assets
        # 确保移动文件时使用正确的文件名
        for file in assets/debian.tar.xz.*; do
          mv "$file" "assets/$(basename "$file")"
        done

    - name: Build project
      run: |
        flutter build apk --target-platform android-arm64 --split-per-abi --obfuscate --split-debug-info=tiny_computer/sdi
      # 使用 Flutter 构建 APK

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-apk
        path: build/app/outputs/flutter-apk/app-arm64.apk
      # 上传构建好的 APK 为工件
